services:
  api:
    build: .
    container_name: mindx-api

    ports:
      - "8000:8000"

    depends_on:
      - postgres

    restart: unless-stopped

  postgres:
    image: postgres:17

    container_name: mindx-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: mindx
      POSTGRES_PASSWORD: mindx123
      POSTGRES_DB: mindxdb

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: